### PR TITLE
Setup-Schedule-Controller

### LINKED ISSUE #43: Setup Schedules Controller

### PR DESCRIPTION
**Pull request by MESC2020**
Also added Token-Auth. in UserService (can be removed if preferred)
closes #43

### CODE REVIEW

**Comment by MESC2020** [comment]
Methods return values are set to VOID since these classes are not existing yet

**Comment by Taremeh** [comment]
Just a quick heads up: This pull request could result in merge conflicts with #46 since non-necessary code has been removed.

I also had a quick look on the code. Regarding the authorization: 
The current method only checks whether the request can provide a valid token for any existing user, but not for the user for whom changes will be made (e.g. User X will be able to request actions for User Y). Furthermore it is important to specify what the method does (or what a header variable stands for), e.g. "auth-token" would be clearer than just "Authorization".

**Comment by MESC2020** [comment]
> Just a quick heads up: This pull request could result in merge conflicts with #46 since non-necessary code has been removed.
> 
> I also had a quick look on the code. Regarding the authorization:
> The current method only checks whether the request can provide a valid token for any existing user, but not for the user for whom changes will be made (e.g. User X will be able to request actions for User Y). Furthermore it is important to specify what the method does (or what a header variable stands for), e.g. "auth-token" would be clearer than just "Authorization".

I added the auth-token to avoid any compiler errors, to make sure there's already a certain base we can build on and to make sure that the 4## Status Codes are covered as well. How exactly we'll implement the auth. should be generalized/decided anyway in a future step. 

Further, checks if X is allowed to change X depends on other UserService methods and has yet to be implemented. And, if we generate a complete new token everytime a user logs in, it should already cover this case if I don't misunderstand it.

Regarding the naming convention, I wasn't aware of that.

All in all, I can delete/adjust the auth. part again if preferred or one can delete/adjust it in the future. Thoughts?

**Review by SamuelBruegger — APPROVED** [review]
- looks good to me

**Pull request merged**
